todolist-server:
  build: .
  links:
   - mysql
  ports:
    - "3000:3000"
  volumes:
    - .:/usr/src/app/
  environment:
    NODE_ENV: "development"
    DATABASE_HOST: "mysql"
    DATABASE_USER: "root"
    DATABASE_PASSWORD: "password"
    DATABASE: "todoApp"
  working_dir: "/usr/src/app"
  entrypoint: /usr/src/app/node_modules/nodemon/bin/nodemon.js -L --ignore node_modules/ --ignore public/ --ignore .tmp/ /usr/src/app/app.js
mysql:
  image: mysql
  environment:
    MYSQL_ROOT_PASSWORD: "password"
  volumes:
    - "./schema:/docker-entrypoint-initdb.d/"
  ports:
    - "3306:3306"
